name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Check Ruby and Bundler versions
        run: |
          ruby --version
          bundler --version
      - name: Build the Jekyll Site
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build -d _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
